[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./config/"}, { access = "read", path = "./lib/morpho-blue/out/"}]
names = true
sizes = true
via-ir = true
evm_version = "paris"

[profile.default.fuzz]
runs = 32

[profile.default.invariant]
runs = 16
depth = 4

[profile.default.rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"

[profile.default.fmt]
wrap_comments = true


[profile.build]
test = "/dev/null"
script = "/dev/null"
force = true


[profile.test]
via-ir = false


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
