name: Certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        conf:
          - ConsistentState
          - Reverts
          - Roles
          - Tokens

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v4

      - name: Install certora
        run: pip install certora-cli-beta

      - name: Install solc (0.8.19)
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.19

      - name: Install solc (0.8.21)
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.21/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc

      - name: Apply munging
        run: make -C certora munged

      - name: Verify rule ${{ matrix.conf }}
        run: certoraRun certora/confs/${{ matrix.conf }}.conf
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
